### ISSUE TITLE
All Zeros in Accelerometer and gyro data.

### ISSUE THREAD

**Issue by priyanshu-makhiyaviya** [W00ng/ESP32-S3-HMI-V3#2]
Hi,

I am trying to read accelerometer and gyro data using MPU-6050. I am using the ESP32-S3-HMI kit.
I am getting all zeros in the accelerometer and gyro data. However, I can read chip ID, Power management, and other config registers.

Any suggestions for this issue?

Steps Followed:

1) Copied bsp, i2c_bus, and i2c_devices components from ESP32-S3-HMI-V3/components to my application/component

2) Integrated it with my CMakelist.txt 

3) from the main I am calling the below function 

    /* Initialize I2C 400KHz */
    ESP_ERROR_CHECK(bsp_i2c_init(I2C_NUM_0, 400000));

    /* Init MEMS sensor */
    ESP_ERROR_CHECK(mpu6050_init());
    
    /* Get Accelerometer data in loop */
    imu_mpu6050_acquire_acce(&acce_x, &acce_y, &acce_z)

Note: The chip is in wake mode by disabling SLEEP by writing a 0 to the PWR_MGMT_1 (0x6B) register.

**Comment by W00ng** [comment]
Hi,

You can refer to the example sensors to use MPU-6050: 
https://github.com/W00ng/ESP32-S3-HMI-V3/tree/master/examples/sensors

**Comment by priyanshu-makhiyaviya** [comment]
Hi,
Thank you for your response.
Please note that I am already referring to that example.

**Comment by W00ng** [comment]
How about use this to read:
```
mpu6050_acce_value_t acc_val;
mpu6050_gyro_value_t gyro_val;
mpu6050_get_acce(&acc_val);
mpu6050_get_gyro(&gyro_val);
```

**Comment by priyanshu-makhiyaviya** [comment]
Same behavior with this also.

**Comment by W00ng** [comment]
Maybe it‘s’ hardware problem, contact me: aemails@163.com

**Comment by priyanshu-makhiyaviya** [comment]
Hi @W00ng 
It was a hardware issue. I have changed ESP32-S3-HMI and it worked.  

Thank you.
