### ISSUE TITLE
Can not connect wifi after running wifi_scan example

### ISSUE THREAD

**Issue by vanbuong** [W00ng/ESP32-S3-HMI-V3#4]
Idf v4.4.3

![FAED4A05-A201-4013-980C-228AF7FE49E1](https://user-images.githubusercontent.com/20797073/201567733-f9ced497-6447-4079-ae97-5ebba98ccd68.jpeg)
![49DD6473-1D8D-4B44-A7E2-2BE1F0F3D884](https://user-images.githubusercontent.com/20797073/201567750-eb24be27-2a1f-4cba-b4d1-98ae78a5a8f0.jpeg)

**Comment by W00ng** [comment]
Hi,
1. Could you please change another 2.4G hotspot to have a try.
2. Or you download this example and share me the log : https://github.com/espressif/esp-idf/tree/v4.4.3/examples/wifi/fast_scan

**Comment by vanbuong** [comment]
Hi,

The log I got after running example:

x�x���x�x����ESP-ROM:esp32s3-20210327
Build:Mar 27 2021
rst:0x1 (POWERON),boot:0x8 (SPI_FAST_FLASH_BOOT)
SPIWP:0xee
mode:DIO, clock div:1
load:0x3fce3808,len:0x1660
load:0x403c9700,len:0xbb8
load:0x403cc700,len:0x2e8c
entry 0x403c9954
I (24) boot: ESP-IDF v4.4.3 2nd stage bootloader
I (25) boot: compile time 23:24:09
I (25) boot: chip revision: 0
I (26) boot.esp32s3: Boot SPI Speed : 80MHz
I (31) boot.esp32s3: SPI Mode       : DIO
I (36) boot.esp32s3: SPI Flash Size : 2MB
I (40) boot: Enabling RNG early entropy source...
I (46) boot: Partition Table:
I (49) boot: ## Label            Usage          Type ST Offset   Length
I (57) boot:  0 nvs              WiFi data        01 02 00009000 00006000
I (64) boot:  1 phy_init         RF data          01 01 0000f000 00001000
I (72) boot:  2 factory          factory app      00 00 00010000 00100000
I (79) boot: End of partition table
I (83) esp_image: segment 0: paddr=00010020 vaddr=3c070020 size=12b70h ( 76656) map
I (106) esp_image: segment 1: paddr=00022b98 vaddr=3fc95b10 size=04148h ( 16712) load
I (109) esp_image: segment 2: paddr=00026ce8 vaddr=40374000 size=09330h ( 37680) load
I (120) esp_image: segment 3: paddr=00030020 vaddr=42000020 size=6a8bch (436412) map
I (198) esp_image: segment 4: paddr=0009a8e4 vaddr=4037d330 size=087d4h ( 34772) load
I (206) esp_image: segment 5: paddr=000a30c0 vaddr=50000000 size=00010h (    16) load
I (214) boot: Loaded app from partition at offset 0x10000
I (214) boot: Disabling RNG early entropy source...
I (227) cpu_start: Pro cpu up.
I (227) cpu_start: Starting app cpu, entry point is 0x4037520c
0x4037520c: call_start_cpu1 at C:/esp/Espressif/frameworks/esp-idf-v4.4.3/components/esp_system/port/cpu_start.c:148

I (0) cpu_start: App cpu up.
I (241) cpu_start: Pro cpu start user code
I (241) cpu_start: cpu freq: 160000000
I (241) cpu_start: Application information:
I (244) cpu_start: Project name:     fast_scan
I (249) cpu_start: App version:      v4.4.3
I (254) cpu_start: Compile time:     Nov 15 2022 23:23:31
I (260) cpu_start: ELF file SHA256:  6e809e9b9341b156...
I (266) cpu_start: ESP-IDF:          v4.4.3
I (271) heap_init: Initializing. RAM available for dynamic allocation:
I (278) heap_init: At 3FC9D738 len 0004BFD8 (303 KiB): D/IRAM
I (284) heap_init: At 3FCE9710 len 00005724 (21 KiB): STACK/DRAM
I (291) heap_init: At 3FCF0000 len 00008000 (32 KiB): DRAM
I (297) heap_init: At 600FE000 len 00002000 (8 KiB): RTCRAM
I (304) spi_flash: detected chip: winbond
I (308) spi_flash: flash io: dio
W (312) spi_flash: Detected size(8192k) larger than the size in the binary image header(2048k). Using the size in the binary image header.
I (326) sleep: Configure to isolate all GPIO pins in sleep state
I (332) sleep: Enable automatic switching of GPIO sleep configuration
I (339) cpu_start: Starting scheduler on PRO CPU.
I (0) cpu_start: Starting scheduler on APP CPU.
I (400) pp: pp rom version: e7ae62f
I (400) net80211: net80211 rom version: e7ae62f
I (410) wifi:wifi driver task: 3fcf512c, prio:23, stack:6656, core=0
I (410) system_api: Base MAC address is not set
I (410) system_api: read default base MAC address from EFUSE
I (420) wifi:wifi firmware version: 8cb87ff
I (420) wifi:wifi certification version: v7.0
I (420) wifi:config NVS flash: enabled
I (420) wifi:config nano formating: disabled
I (430) wifi:Init data frame dynamic rx buffer num: 32
I (430) wifi:Init management frame dynamic rx buffer num: 32
I (440) wifi:Init management short buffer num: 32
I (440) wifi:Init dynamic tx buffer num: 32
I (450) wifi:Init static tx FG buffer num: 2
I (450) wifi:Init static rx buffer size: 1600
I (460) wifi:Init static rx buffer num: 10
I (460) wifi:Init dynamic rx buffer num: 32
I (460) wifi_init: rx ba win: 6
I (470) wifi_init: tcpip mbox: 32
I (470) wifi_init: udp mbox: 6
I (470) wifi_init: tcp mbox: 6
I (480) wifi_init: tcp tx win: 5744
I (480) wifi_init: tcp rx win: 5744
I (490) wifi_init: tcp mss: 1440
I (490) wifi_init: WiFi IRAM OP enabled
I (490) wifi_init: WiFi RX IRAM OP enabled
I (520) phy_init: phy_version 503,13653eb,Jun  1 2022,17:47:08
I (550) wifi:mode : sta (f4:12:fa:c4:7a:6c)
I (550) wifi:enable tsf
I (940) wifi:new:<4,0>, old:<1,0>, ap:<255,255>, sta:<4,0>, prof:1
I (1910) wifi:state: init -> auth (b0)
I (2910) wifi:state: auth -> init (200)
I (2910) wifi:new:<4,0>, old:<4,0>, ap:<255,255>, sta:<4,0>, prof:1
I (7800) wifi:new:<4,0>, old:<4,0>, ap:<255,255>, sta:<4,0>, prof:1
I (7800) wifi:state: init -> auth (b0)
I (8800) wifi:state: auth -> init (200)
I (8800) wifi:new:<4,0>, old:<4,0>, ap:<255,255>, sta:<4,0>, prof:1
I (11290) wifi:new:<4,0>, old:<4,0>, ap:<255,255>, sta:<4,0>, prof:1
I (11290) wifi:state: init -> auth (b0)
I (12290) wifi:state: auth -> init (200)
I (12290) wifi:new:<4,0>, old:<4,0>, ap:<255,255>, sta:<4,0>, prof:1
I (14760) wifi:new:<4,0>, old:<4,0>, ap:<255,255>, sta:<4,0>, prof:1
I (14760) wifi:state: init -> auth (b0)
I (15760) wifi:state: auth -> init (200)
I (15770) wifi:new:<4,0>, old:<4,0>, ap:<255,255>, sta:<4,0>, prof:1
I (18250) wifi:new:<4,0>, old:<4,0>, ap:<255,255>, sta:<4,0>, prof:1
I (18250) wifi:state: init -> auth (b0)
I (19250) wifi:state: auth -> init (200)
I (19250) wifi:new:<4,0>, old:<4,0>, ap:<255,255>, sta:<4,0>, prof:1
I (21730) wifi:new:<4,0>, old:<4,0>, ap:<255,255>, sta:<4,0>, prof:1
I (21730) wifi:state: init -> auth (b0)
I (22730) wifi:state: auth -> init (200)
I (22730) wifi:new:<4,0>, old:<4,0>, ap:<255,255>, sta:<4,0>, prof:1
I (25210) wifi:new:<4,0>, old:<4,0>, ap:<255,255>, sta:<4,0>, prof:1
I (25210) wifi:state: init -> auth (b0)
I (26210) wifi:state: auth -> init (200)
I (26210) wifi:new:<4,0>, old:<4,0>, ap:<255,255>, sta:<4,0>, prof:1
I (28690) wifi:new:<4,0>, old:<4,0>, ap:<255,255>, sta:<4,0>, prof:1
I (28690) wifi:state: init -> auth (b0)
I (29690) wifi:state: auth -> init (200)
I (29690) wifi:new:<4,0>, old:<4,0>, ap:<255,255>, sta:<4,0>, prof:1
I (32170) wifi:new:<4,0>, old:<4,0>, ap:<255,255>, sta:<4,0>, prof:1
I (32170) wifi:state: init -> auth (b0)
I (33170) wifi:state: auth -> init (200)
I (33170) wifi:new:<4,0>, old:<4,0>, ap:<255,255>, sta:<4,0>, prof:1
I (35650) wifi:new:<4,0>, old:<4,0>, ap:<255,255>, sta:<4,0>, prof:1
I (35650) wifi:state: init -> auth (b0)
I (36650) wifi:state: auth -> init (200)
I (36660) wifi:new:<4,0>, old:<4,0>, ap:<255,255>, sta:<4,0>, prof:1
I (39140) wifi:new:<4,0>, old:<4,0>, ap:<255,255>, sta:<4,0>, prof:1
I (39140) wifi:state: init -> auth (b0)
I (40140) wifi:state: auth -> init (200)
I (40140) wifi:new:<4,0>, old:<4,0>, ap:<255,255>, sta:<4,0>, prof:1
I (42620) wifi:new:<4,0>, old:<4,0>, ap:<255,255>, sta:<4,0>, prof:1
I (42620) wifi:state: init -> auth (b0)
I (43620) wifi:state: auth -> init (200)
I (43620) wifi:new:<4,0>, old:<4,0>, ap:<255,255>, sta:<4,0>, prof:1
I (46100) wifi:new:<4,0>, old:<4,0>, ap:<255,255>, sta:<4,0>, prof:1
I (46100) wifi:state: init -> auth (b0)
I (47100) wifi:state: auth -> init (200)
I (47100) wifi:new:<4,0>, old:<4,0>, ap:<255,255>, sta:<4,0>, prof:1
I (49580) wifi:new:<4,0>, old:<4,0>, ap:<255,255>, sta:<4,0>, prof:1
I (49580) wifi:state: init -> auth (b0)
I (50580) wifi:state: auth -> init (200)
I (50580) wifi:new:<4,0>, old:<4,0>, ap:<255,255>, sta:<4,0>, prof:1
I (53060) wifi:new:<4,0>, old:<4,0>, ap:<255,255>, sta:<4,0>, prof:1
I (53060) wifi:state: init -> auth (b0)
I (54060) wifi:state: auth -> init (200)
I (54060) wifi:new:<4,0>, old:<4,0>, ap:<255,255>, sta:<4,0>, prof:1
I (56540) wifi:new:<4,0>, old:<4,0>, ap:<255,255>, sta:<4,0>, prof:1
I (56550) wifi:state: init -> auth (b0)
I (57550) wifi:state: auth -> init (200

**Comment by W00ng** [comment]
Hi ,
From the log, I didn't see any errors, it seems run into a loop.
1. Have you ever try another 2.4G hotspot?
2. If you have other esp32 board, you can also run this example for a test.
[ok-log.txt](https://github.com/W00ng/ESP32-S3-HMI-V3/files/10017173/ok-log.txt)

**Comment by vanbuong** [comment]
Hi,

I have tried another wifi hotspot and it's working now.  This issue didn't happen on my other esp32 so I thought it was an HW issue.
Thanks for your help

**Comment by W00ng** [comment]
ok, thank you for your feedback.
